import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      colors: {
        "neutral-base": "var(--neutral-base)",
        "neutral-bg-subtle": "var(--neutral-bg-subtle)",
        "neutral-bg": "var(--neutral-bg)",
        "neutral-bg-hover": "var(--neutral-bg-hover)",
        "neutral-bg-active": "var(--neutral-bg-active)",
        "neutral-line": "var(--neutral-line)",
        "neutral-border": "var(--neutral-border)",
        "neutral-border-hover": "var(--neutral-border-hover)",
        "neutral-solid": "var(--neutral-solid)",
        "neutral-solid-hover": "var(--neutral-solid-hover)",
        "neutral-text": "var(--neutral-text)",
        "neutral-text-contrast": "var(--neutral-text-contrast)",

        "primary-base": "var(--primary-base)",
        "primary-bg-subtle": "var(--primary-bg-subtle)",
        "primary-bg": "var(--primary-bg)",
        "primary-bg-hover": "var(--primary-bg-hover)",
        "primary-bg-active": "var(--palmary-bg-active)",
        "primary-line": "var(--primary-line)",
        "primary-border": "var(--primary-border)",
        "primary-border-hover": "var(--primary-border-hover)",
        "primary-solid": "var(--primary-solid)",
        "primary-solid-hover": "var(--primary-solid-hover)",
        "primary-text": "var(--primary-text)",
        "primary-text-contrast": "var(--primary-text-contrast)",

        "secondary-base": "var(--secondary-base)",
        "secondary-bg-subtle": "var(--secondary-bg-subtle)",
        "secondary-bg": "var(--secondary-bg)",
        "secondary-bg-hover": "var(--secondary-bg-hover)",
        "secondary-bg-active": "var(--secondary-bg-active)",
        "secondary-line": "var(--secondary-line)",
        "secondary-border": "var(--secondary-border)",
        "secondary-border-hover": "var(--secondary-border-hover)",
        "secondary-solid": "var(--secondary-solid)",
        "secondary-solid-hover": "var(--secondary-solid-hover)",
        "secondary-text": "var(--secondary-text)",
        "secondary-text-contrast": "var(--secondary-text-contrast)",

        "success-base": "var(--success-base)",
        "success-bg-subtle": "var(--success-bg-subtle)",
        "success-bg": "var(--success-bg)",
        "success-bg-hover": "var(--success-bg-hover)",
        "success-bg-active": "var(--success-bg-active)",
        "success-line": "var(--success-line)",
        "success-bg-border": "var(--success-border)",
        "success-bg-hover-hover": "var(--success-border-hover)",
        "success-solid": "var(--success-solid)",
        "success-solid-hover": "var(--success-solid-hover)",
        "success-text": "var(--success-text)",
        "success-text-contrast": "var(--success-text-contrast)",

        "warning-base": "var(--warning-base)",
        "warning-bg-subtle": "var(--warning-bg-subtle)",
        "warning-bg": "var(--warning-bg)",
        "warning-bg-hover": "var(--warning-bg-hover)",
        "warning-bg-active": "var(--warning-bg-active)",
        "warning-line": "var(--warning-line)",
        "warning-border": "var(--warning-border)",
        "warning-border-hover": "var(--warning-border-hover)",
        "warning-solid": "var(--warning-solid)",
        "warning-solid-hover": "var(--warning-solid-hover)",
        "warning-text": "var(--warning-text)",
        "warning-text-contrast": "var(--warning-text-contrast)",

        "danger-base": "var(--danger-base)",
        "danger-bg-subtle": "var(--danger-bg-subtle)",
        "danger-bg": "var(--danger-bg)",
        "danger-bg-hover": "var(--danger-bg-hover)",
        "danger-bg-active": "var(--danger-bg-active)",
        "danger-line": "var(--danger-line)",
        "danger-border": "var(--danger-border)",
        "danger-border-hover": "var(--danger-border-hover)",
        "danger-solid": "var(--danger-solid)",
        "danger-solid-hover": "var(--danger-solid-hover)",
        "danger-text": "var(--danger-text)",
        "danger-text-contrast": "var(--danger-text-contrast)",

        "info-base": "var(--info-base)",
        "info-bg-subtle": "var(--info-bg-subtle)",
        "info-bg": "var(--info-bg)",
        "info-bg-hover": "var(--info-bg-hover)",
        "info-bg-active": "var(--info-bg-active)",
        "info-line": "var(--info-line)",
        "info-border": "var(--info-border)",
        "info-border-hover": "var(--info-border-hover)",
        "info-solid": "var(--info-solid)",
        "info-solid-hover": "var(--info-solid-hover)",
        "info-text": "var(--info-text)",
        "info-text-contrast": "var(--info-text-contrast)",
      },
    },
  },
  plugins: [],
};
export default config;
